# Generated by Django 2.2.16 on 2020-11-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0002_auto_20200629_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='', max_length=256, upload_to='instagram/'),
        ),
    ]
