# Generated by Django 2.2.16 on 2020-11-05 03:47

import os
from configparser import RawConfigParser

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _get_username():
    _env_path = settings.BASE_DIR + '/env.ini'

    if os.path.exists(_env_path):
        env = RawConfigParser()
        env.read(_env_path)
        _settings = env['instagram']
    else:
        _settings = settings.INSTAGRAM_PROFILE

    return _settings.get('account', None)


def forwards(apps, schema_editor):
    # Create a Profile instance and update all posts with this profile
    Profile = apps.get_model('instagram_profile', 'Profile')
    Post = apps.get_model('instagram_profile', 'Post')
    username = _get_username()
    if username:
        profile = Profile.objects.create(username=username)
        Post.objects.all().update(profile=profile)


def backwards(apps, schema_editor):
    # Create a Profile instance and update all posts with this profile
    Profile = apps.get_model('instagram_profile', 'Profile')
    Post = apps.get_model('instagram_profile', 'Post')

    Post.objects.all().update(profile=None)
    username = _get_username()
    if username:
        Profile.objects.filter(username=username).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0002_auto_20200629_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('access_token', models.CharField(blank=True, help_text='The long lived access token', max_length=256)),
                ('expires_at', models.DateTimeField(blank=True, help_text='The expiry of the stored long lived access token', null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'instagram_profile',
                'ordering': ['username'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='', max_length=256, upload_to='instagram/'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instagram_profile.Profile'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
