# Generated by Django 2.2.16 on 2020-11-04 05:21

from django.db import migrations, models
import django.db.models.deletion
from configparser import RawConfigParser
from django.conf import settings
import os


def _get_username():
    _env_path = settings.BASE_DIR + '/env.ini'

    if os.path.exists(_env_path):
        env = RawConfigParser()
        env.read(_env_path)
        _settings = env['instagram']
    else:
        _settings = settings.INSTAGRAM_PROFILE

    return _settings['account']


def forwards(apps, schema_editor):
    # Create a Profile instance and update all posts with this profile
    Profile = apps.get_model('instagram_profile', 'Profile')
    Post = apps.get_model('instagram_profile', 'Post')

    profile = Profile.objects.create(username=_get_username())
    Post.objects.all().update(profile=profile)


def backwards(apps, schema_editor):
    # Create a Profile instance and update all posts with this profile
    Profile = apps.get_model('instagram_profile', 'Profile')
    Post = apps.get_model('instagram_profile', 'Post')

    Post.objects.all().update(profile=None)
    Profile.objects.filter(username=_get_username()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0003_auto_20201104_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'instagram_profile',
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instagram_profile.Profile'),
        ),
        migrations.RunPython(forwards, backwards)
    ]
