# Generated by Django 2.2.16 on 2020-11-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0004_auto_20201104_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.CharField(blank=True, help_text='The long lived access token', max_length=256),
        ),
        migrations.AddField(
            model_name='profile',
            name='expires',
            field=models.DateTimeField(blank=True, help_text='The expiry of the stored long lived access token', null=True),
        ),
    ]
