# Generated by Django 2.2.16 on 2020-11-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0005_auto_20201104_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='expires',
            new_name='expires_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
