# Generated by Django 3.0.1 on 2020-01-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('CAROUSEL_ALBUM', 'Album'), ('VIDEO', 'Video')], default='IMAGE', max_length=20)),
                ('permalink', models.CharField(max_length=256)),
                ('caption', models.CharField(default='', max_length=100)),
                ('thumbnail', models.CharField(default='', max_length=256)),
                ('children', models.TextField(default='')),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'instagram_posts',
                'ordering': ['-created'],
            },
        ),
    ]
